env:
  browser: true
  amd: true
extends: 'eslint:recommended'
# globals:
#   define: true
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - warn
